#!/bin/bash
# install video2audio
# https://github.com/rofidoang03/video2audio

apt-get update -y
apt-get install ffmpeg -y
mkdir "/root/video2audio"
mkdir "/root/video2audio/conversion_results"
program="video2audio"
chmod a+rwx "${program}"
cp "${program}" /usr/bin/
echo "Installation completed."
exit 0
