#!/bin/bash

chmod a+rwx /src/*

read -p "Apakah Anda ingin menginstal kvka [Y/n] : " n
if [ "$n" == "Y" ] || [ "$n" == "y" ]; then
    ./cek_koneksi_internet
elif [ "$n" == "N" ] || [ "$n" == "n" ]; then
    exit 0
else
    echo "[x] Masukan tidak valid."
    exit 1
fi
