#!/bin/bash

apt-get update -y
apt-get install ffmpeg -y
mkdir -p "/root/video2audio/conversion_results"
program="video2audio"
chmod a+rwx "${program}"
mv "${program}" /usr/bin/
echo "Installation completed."
exit 0
