#!/bin/bash
  
if [ "$EUID" -ne 0 ]; then
    echo "[x] Jalankan sebagai root."
    exit 1
fi
k="Selamat datang di menu instalasi kvka."
echo -n "$k" | pv -qL 10
echo -e "\n"
read -p "Apakah Anda ingin menginstal kvka [Y/n] : " n
if [ "$n" == "Y" ] || [ "$n" == "y" ]; then
    echo -e "\n[*] Mengecek koneksi internet."
    sleep 3
    ping -c 1 google.com >> /dev/null 2>&1
    if [ $? -eq 0 ]; then
        read -p "[+] Anda memiliki koneksi internet, tekan Enter untuk melanjutkan proses instalasi... " d
        echo -e "\n[*] Memperbaharui repositori."
        apt-get update -y >> /dev/null 2>&1
        echo "[+] Repositori berhasil diperbaharui."
        echo "[*] Menginstal FFmpeg."
        apt-get install ffmpeg -y >> /dev/null 2>&1
        echo "[+] FFmpeg berhasil diinstal."
        echo "[*] Menginstal pv."
        apt-get install pv -y >> /dev/null 2>&1
        echo "[+] pv berhasil diinstal."
        mkdir -p "/root/kvka/hasil_konversi"
        program="kvka"
        chmod a+rwx "${program}"
        mv "${program}" /usr/bin/
        echo "[+] Instalasi selesai."
        sleep 1
        echo "[+] Untuk menjalankan kvka ketikkan perintah 'kvka'."
        exit 0
    else
        echo "[x] Anda tidak memiliki koneksi internet. Pastikan Anda terhubung ke internet untuk menginstal kvka."
        exit 1
    fi
elif [ "$n" == "N" ] || [ "$n" == "n" ]; then
    exit 0
else
    echo "[x] Masukan tidak valid."
    exit 1
fi
