#!/bin/bash
# video2audio
# video2audio is a simple Bash script created to convert video files into audio files on the Linux (Debian/Ubuntu) operating system using the FFmpeg software.
# https://github.com/rofidoang03/video2audio.git

read -p "Enter video file name: " v
read -p "Enter audio file name: " a

ffmpeg -i "${v}" -vn -acodec libmp3lame "${a}"
mv "${a}" /root/video2audio/conversion_results

echo "Conversion completed."
echo "Conversion results are saved in '/root/video2audio/conversion_results'."
