#!/bin/bash
# video2audio
# Convert video to audio using Ffmpeg."
# https://github.com/rofidoang03/video2audio.git

read -p "Enter video file name: " v
read -p "Enter audio file name: " a

ffmpeg -i "${v} -vm -acodec libmp3lame ${a}

echo "Conversion completed."
echo "Conversion results are saved in '/root/video2audio/conversion_results'."
