#!/bin/bash

echo -e "\n[*] Mengecek koneksi internet."
sleep 3
ping -c 1 google.com >> /dev/null 2>&1
if [ $? -eq 0 ]; then
    read -p "[+] Anda memiliki koneksi internet, tekan Enter untuk melanjutkan proses instalasi... " d
    bash instal_kvka
else
    echo "[x] Anda tidak memiliki koneksi internet. Pastikan Anda terhubung ke internet untuk menginstal kvka."
fi
