#!/bin/bash

clear

k_1="Selamat datang di KVKA"
k_2="KVKA adalah skrip Bash sederhana yang dibuat untuk mengonversi file video menjadi file audio menggunakan perangkat lunak FFmpeg."

echo -n "$k_1" | pv -qL 10
echo -e "\n"
echo -n "$k_2" | pv -qL 10
echo -e "\n"

read -p "Masukkan nama file video: " v

if [ -e "$v" ]; then
    read -p "Masukkan nama file audio: " a
    echo "[*] Melakukan konversi..."
    ffmpeg -i "${v}" -vn -acodec libmp3lame "${a}" >> /dev/null 2>&1
    mv "${a}" /root/kvka/hasil_konversi
    echo "[+] Konversi selesai."
    echo "[+] Hasil konversi disimpan di folder '/root/kvka/hasil_konversi'."
    exit 0

else
    echo "[x] File '$v' tidak ditemukan."
    exit 1
fi
