#!/bin/bash

clear

# Variabel warna
b="\e[1;34m"
m="\e[1;31m"
h="\e[1;32m"
r="\e[0m"

k_1="Selamat datang di kvka"
k_2="kvka adalah skrip Bash sederhana yang dibuat untuk mengkonversi file video menjadi file audio menggunakan FFmpeg."

echo -n "$k_1" | pv -qL 10
echo -e "\n"
echo -n "$k_2" | pv -qL 10
echo -e "\n"

read -p "Masukkan nama file video : " v

if [ -e "$v" ]; then
    read -p "Masukkan nama file audio : " a
    echo -e "\n${b}[*] ${r}Melakukan konversi..."
    ffmpeg -i "${v}" -vn -acodec libmp3lame "${a}" >> /dev/null 2>&1
    mv "${a}" /usr/share/kvka/hasil_konversi
    echo -e "${h}\n[+] ${r}Konversi selesai."
    echo -e "${h}[+] ${r}Hasil konversi disimpan di folder '${h}/usr/share/kvka/hasil_konversi${r}'."
    exit 0

else
    echo "[x] File '$v' tidak ditemukan."
    exit 1
fi
